// Shared control catalog for ASI-1

export interface Control {
  ref: string;
  name: string;
  passCriterion: string;
  owaspMap: string;
  profiles: string[];
  isCore: boolean;
  domain: string;
}

export const controls: Control[] = [
  // Governance & accountability
  {
    ref: "GOV-1",
    name: "AI security ownership",
    passCriterion: "A named role is accountable for AI security; documented and current",
    owaspMap: "NIST Govern",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "Governance & accountability",
  },
  {
    ref: "GOV-2",
    name: "AI acceptable-use policy",
    passCriterion: "Policy defines approved AI systems, allowed data, prohibited uses; staff attest",
    owaspMap: "Sensitive Info Disclosure",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: false,
    domain: "Governance & accountability",
  },
  {
    ref: "GOV-3",
    name: "AI risk register",
    passCriterion: "AI-specific risks identified, rated, reviewed on a cadence",
    owaspMap: "NIST Map",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Governance & accountability",
  },
  // AI asset inventory & data flow
  {
    ref: "INV-1",
    name: "Model & system inventory",
    passCriterion: "Every in-scope model, endpoint, AI feature inventoried with owner and purpose",
    owaspMap: "Supply Chain",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "AI asset inventory & data flow",
  },
  {
    ref: "INV-2",
    name: "Data-flow mapping",
    passCriterion: "Data flows in/out of each AI system documented, incl. what reaches third-party models",
    owaspMap: "Sensitive Info Disclosure",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "AI asset inventory & data flow",
  },
  {
    ref: "INV-3",
    name: "Shadow-AI detection",
    passCriterion: "Process to detect unsanctioned AI tools handling company/customer data",
    owaspMap: "Supply Chain",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: false,
    domain: "AI asset inventory & data flow",
  },
  // Data governance
  {
    ref: "DAT-1",
    name: "Sensitive-data controls at input",
    passCriterion: "Sensitive data sent to models is classified and minimized or redacted per policy",
    owaspMap: "Sensitive Info Disclosure",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "Data governance",
  },
  {
    ref: "DAT-2",
    name: "Training/tuning data governance",
    passCriterion: "Provenance of training/fine-tuning data recorded; sources vetted for poisoning and licensing",
    owaspMap: "Data & Model Poisoning",
    profiles: ["Builder"],
    isCore: false,
    domain: "Data governance",
  },
  {
    ref: "DAT-3",
    name: "Retrieval-source integrity",
    passCriterion: "RAG/vector sources access-controlled and validated against tampering",
    owaspMap: "Vector & Embedding Weaknesses",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Data governance",
  },
  {
    ref: "DAT-4",
    name: "Data retention & deletion",
    passCriterion: "Prompts, outputs, embeddings have defined retention/deletion honoring user rights",
    owaspMap: "Sensitive Info Disclosure",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: false,
    domain: "Data governance",
  },
  // Input & prompt security
  {
    ref: "INP-1",
    name: "Prompt-injection defenses",
    passCriterion: "Untrusted input separated from instructions; direct/indirect injection defenses in place and tested",
    owaspMap: "Prompt Injection",
    profiles: ["Deployer", "Builder"],
    isCore: true,
    domain: "Input & prompt security",
  },
  {
    ref: "INP-2",
    name: "Input validation & limits",
    passCriterion: "Inputs validated, typed, length-limited before reaching the model",
    owaspMap: "Prompt Injection",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Input & prompt security",
  },
  {
    ref: "INP-3",
    name: "System-prompt protection",
    passCriterion: "System prompts contain no secrets and are protected against leakage",
    owaspMap: "System Prompt Leakage",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Input & prompt security",
  },
  // Output handling
  {
    ref: "OUT-1",
    name: "Output encoding & sanitization",
    passCriterion: "Model output treated as untrusted and sanitized before use in code, queries, rendering",
    owaspMap: "Improper Output Handling",
    profiles: ["Deployer", "Builder"],
    isCore: true,
    domain: "Output handling",
  },
  {
    ref: "OUT-2",
    name: "Output disclosure controls",
    passCriterion: "Outputs checked so models don't reveal secrets, other users' data, or restricted content",
    owaspMap: "Sensitive Info Disclosure",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Output handling",
  },
  {
    ref: "OUT-3",
    name: "Grounding & accuracy safeguards",
    passCriterion: "High-impact outputs grounded, cited, or human-reviewed to limit harmful misinformation",
    owaspMap: "Misinformation",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Output handling",
  },
  // Model & endpoint access control
  {
    ref: "ACC-1",
    name: "Endpoint authentication",
    passCriterion: "Model/inference endpoints require authentication; no anonymous access",
    owaspMap: "Supply Chain",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "Model & endpoint access control",
  },
  {
    ref: "ACC-2",
    name: "Least-privilege keys",
    passCriterion: "API keys/model credentials scoped, rotated, stored in a secret manager",
    owaspMap: "Supply Chain",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "Model & endpoint access control",
  },
  {
    ref: "ACC-3",
    name: "Model-theft protection",
    passCriterion: "Model weights/artifacts access-controlled and monitored for exfiltration",
    owaspMap: "Data & Model Poisoning",
    profiles: ["Builder"],
    isCore: false,
    domain: "Model & endpoint access control",
  },
  // Agent & tool-use controls
  {
    ref: "AGT-1",
    name: "Least-privilege agency",
    passCriterion: "Agent tools/permissions are the minimum required; high-impact actions allow-listed",
    owaspMap: "Excessive Agency",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Agent & tool-use controls",
  },
  {
    ref: "AGT-2",
    name: "Human-in-the-loop gates",
    passCriterion: "Irreversible/high-impact agent actions require human approval",
    owaspMap: "Excessive Agency",
    profiles: ["Deployer", "Builder"],
    isCore: true,
    domain: "Agent & tool-use controls",
  },
  {
    ref: "AGT-3",
    name: "Action logging & limits",
    passCriterion: "Agent actions logged and rate/scope-limited so a compromised agent has bounded blast radius",
    owaspMap: "Excessive Agency",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Agent & tool-use controls",
  },
  // Supply chain
  {
    ref: "SUP-1",
    name: "Model & vendor vetting",
    passCriterion: "Third-party models, APIs, AI vendors security-reviewed before use",
    owaspMap: "Supply Chain",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: false,
    domain: "Supply chain",
  },
  {
    ref: "SUP-2",
    name: "Component provenance",
    passCriterion: "Model files, plugins, libraries integrity-checked and from trusted registries",
    owaspMap: "Supply Chain",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Supply chain",
  },
  // Monitoring, logging & incident response
  {
    ref: "MON-1",
    name: "AI-aware logging",
    passCriterion: "Prompts, outputs, agent actions logged with enough detail to investigate an incident",
    owaspMap: "NIST Manage",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "Monitoring, logging & incident response",
  },
  {
    ref: "MON-2",
    name: "Abuse & anomaly monitoring",
    passCriterion: "Injection attempts, abuse, anomalous usage detected and alerted",
    owaspMap: "Prompt Injection",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Monitoring, logging & incident response",
  },
  {
    ref: "MON-3",
    name: "AI incident response plan",
    passCriterion: "Response plan covers AI-specific incidents and is tested at least annually",
    owaspMap: "NIST Manage",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: true,
    domain: "Monitoring, logging & incident response",
  },
  // Resilience & abuse prevention
  {
    ref: "RES-1",
    name: "Rate & cost limits",
    passCriterion: "Per-user and per-key rate, token, and cost limits enforced",
    owaspMap: "Unbounded Consumption",
    profiles: ["Consumer", "Deployer", "Builder"],
    isCore: false,
    domain: "Resilience & abuse prevention",
  },
  {
    ref: "RES-2",
    name: "Availability safeguards",
    passCriterion: "Controls against resource-exhaustion and denial-of-wallet attacks",
    owaspMap: "Unbounded Consumption",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Resilience & abuse prevention",
  },
  // Testing & red-teaming
  {
    ref: "TST-1",
    name: "AI security testing",
    passCriterion: "AI systems tested against ASI-1 threats before release and on change",
    owaspMap: "Prompt Injection",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Testing & red-teaming",
  },
  {
    ref: "TST-2",
    name: "Adversarial red-teaming",
    passCriterion: "Periodic authorized adversarial testing against relevant MITRE ATLAS tactics",
    owaspMap: "Data & Model Poisoning",
    profiles: ["Deployer", "Builder"],
    isCore: false,
    domain: "Testing & red-teaming",
  },
];
